accounts/urls.py
# accounts/urls.py

from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name='signup')
]

bookstore/urls.py
# bookstore/urls.py
from django.urls import path
from .views import BookstoreListView, BookstoreCreateView, BookstoreUpdateView, BookstoreDetailView, BookstoreDeleteView

urlpatterns = [
    path("book/new/", BookstoreCreateView.as_view(), name="book_new"),
    path("book/<int:pk>/", BookstoreDetailView.as_view(), name="book_detail"),
    path("book/<int:pk>/edit", BookstoreUpdateView.as_view(), name="book_edit"),
    path("book/<int:pk>/delete", BookstoreDeleteView.as_view(), name="book_delete"),
    path("", BookstoreListView.as_view(), name="home"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include("accounts.urls")),
    path("", include("bookstore.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

bookstore/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=50)
    year = models.IntegerField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})
        # return reverse("home")

accounts/views.py
# accounts/views.py

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

bookstore/views.py
# bookstore/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Book


class BookstoreListView(ListView):
    model = Book
    template_name = "home.html"
    paginate_by = 10                # specify max number in a page for pagination


class BookstoreDetailView(DetailView):
    model = Book
    template_name = "book_detail.html"


class BookstoreCreateView(CreateView):
    model = Book
    template_name = "book_new.html"
    fields = ["title", "author", "year"]
    success_url = reverse_lazy("home")


class BookstoreUpdateView(UpdateView):
    model = Book
    template_name = "book_edit.html"
    fields = ["title", "author", "year"]


class BookstoreDeleteView(DeleteView):
    model = Book
    template_name = "book_delete.html"
    success_url = reverse_lazy("home")

templates/base.html
<!--templates/base.html-->
{% load static %}

<html>
    <title>Bookstore App</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="static/css/base.css">
    <body>
    <main role="main" class="container">
        <div class="starter-template">
            <header>
                <h1><a href="{% url 'home' %}">BOOKSTORE</a></h1>
<!--                <form class="form-inline mt-2 mt-md-0">-->
<!--                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
<!--                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--                </form>-->
            </header>

            {% block content %}
            {% endblock content %}



        </div>
    </main><!-- /.container -->
    </body>
</html>

templates/book_delete.html
<!--templates/book_delete.html-->
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Delete book entry</h2>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ book.title }}" entry?</p>
    <input class="btn btn-success" type="submit" value="Confirm">
</form>

{% endblock content %}

templates/book_detail.html
<!--templates/book_detail.html-->
{% extends "base.html" %}

{% block content %}
<div class="book-entry">
    <h2>{{ object.title }}</h2>
    <p>By {{ object.author }} ({{ object.year }})</p>
    <a class="btn btn-primary" href="{% url 'book_edit' book.pk %}">Edit</a>
    <a class="btn btn-danger" href="{% url 'book_delete' book.pk %}">Delete</a>
</div>

{% endblock content %}

templates/book_edit.html
<!--templates/book_edit.html-->
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Edit book entry</h2>
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-success" type="submit" value="Update">
</form>

{% endblock content %}

templates/book_new.html
<!--templates/book_new.html-->
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>New book</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-success" type="submit" value="Save">
</form>
{% endblock content %}

templates/home.html
<!--templates/home.html-->
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}
    <p>Hello {{ user.username }}!</p>
    <a href="{% url 'logout' %}">Log Out</a>

    <div>
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Book Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Publication Year</th>
                </tr>
            </thead>
            <tbody>
                {% for book in book_list %}
                <tr>
                    <td><a href="{% url 'book_detail' book.pk %}">{{ book.title }}</a></td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.year }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!--Paginating ListView-->
        {% if is_paginated %}
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}

                </span>
            </div>
        {% endif %}

        <a class="btn btn-primary" href="{% url 'book_new' %}">New Book</a>
    <!--    <a class="btn btn-danger" href="">Delete</a>-->
    </div>


{% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a> |
    <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}

{% endblock content %}